### ISSUE TITLE
generate the deb file but still can't work after installed

### ISSUE THREAD

**Issue by gogongxt** [wangling12/ncm-patch-script#5]
# generate the deb file but still can't work after installed
Use `bash patch_ncmi_deb.sh` and generate the `custom_netease-cloud-music.deb` file.
Use `dpkg -i custom_netease-cloud-music.deb` and open the netease-music.
Click the icon and nothing happened and still can't open the software.

**Comment by gogongxt** [comment]
Open the software in terminal and take the error :
/opt/netease/netease-cloud-music/netease-cloud-music: error while loading shared libraries: libvlc.so.5: cannot open shared object file: No such file or directory

**Comment by wangling12** [comment]
Please upload the output of the script so that we can see what happened.

**Comment by IgararA** [comment]
This problem can be solved by downloading vlc player `sudo apt install vlc`

**Comment by wangling12** [comment]
It seems that this is still caused by the vlc compile failed. It should be no problem now.
If the problem still exists, please re open the issue at any time
