### ISSUE TITLE
这个报错是什么问题呢

### ISSUE THREAD

**Issue by yifang5775** [wangling12/ncm-patch-script#8]
/home/fred/patch_ncmi_deb.sh: 第 32 行： cd: vlc-3*: 没有那个文件或目录
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/modules/access/http/resource.c b/modules/access/http/resource.c
|index 9a28bb50f3..4919cb3a05 100644
|--- a/modules/access/http/resource.c
|+++ b/modules/access/http/resource.c
--------------------------
File to patch:

**Comment by yifang5775** [comment]
下载了vlc的源码后解决这个报错了

**Comment by wangling12** [comment]
主要是deb-src没打开
